# Generated by Django 3.2.5 on 2021-09-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=32, verbose_name='guid')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
            ],
            options={
                'db_table': 'player_index',
                'managed': False,
            },
        ),
    ]
