# Generated by Django 3.2.5 on 2021-09-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_playerindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, verbose_name='Hostname')),
                ('hostname_plain', models.CharField(max_length=64, verbose_name='Hostname plain')),
                ('ip', models.CharField(max_length=64, verbose_name='IP')),
                ('port', models.IntegerField(verbose_name='Port')),
            ],
            options={
                'db_table': 'game_server',
                'managed': False,
            },
        ),
    ]
